import type { Metadata } from 'next'
import './globals.css'

import ThemeRegistry from '@/components/Providers/ThemeRegistry'
import { PropsWithChildren } from 'react'
import NavbarContainer from '@/containers/NavbarContainer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <NavbarContainer />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  )
}
