query GetCategoryHeroById($id: String!) {
  categoryHero(id: $id) {
    subtitle
    title
    sxStyles
    image{
      description
      url
      height
      width
    }
    cta{
      classNames
      text
      id
      sxStyles
      image{
        description
        url
      }
    }
  }
}
