query GeMiddlePages {
  middlePageCollection {
    items {
      sys {
        id
      }
      slug
      title
      externalHref
      childrenPagesCollection(limit: 4) {
        items {
          isInNavbar
          slug
          title
          externalHref
        }
      }
    }
  }
}
