query GetPageBySlug($slug: String!) {
  pageCollection(where: { slug: $slug }, limit: 1) {
    items {
      slug
      title
      contentCollection(limit: 11) {
        items {
          __typename
          sys {
            id
          }
        }
      }
    }
  }
}
