on:
  push:
    tags:
      - 'docs*'
    paths:
      - 'apps/docs/**'

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Build ui
        working-directory: ./packages/ui-material
        run: |
          pnpm install
          pnpm build
      - name: Build
        working-directory: ./apps/docs
        run: |
          pnpm install
          pnpm build-storybook
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/docs/storybook-static
          destination_dir: docs
